### ISSUE TITLE
Missing flatpak

### ISSUE THREAD

**Issue by LyzardKing** [popey/unsnap#12]
# Drag and drop the missingflatpak.txt generated by unsnap to this issue. That's all!

Not many additions in this list..

[missingflatpak.txt](https://github.com/popey/unsnap/files/8421965/missingflatpak.txt)

**Comment by popey** [comment]
Thanks for submitting. I think in future, I will want to collate all these missing ones and have unsnap know that they're missing, up front. For now I'll close this one, as we know they're all missing.
