### ISSUE TITLE
Should log out or reboot after installing flatpak itself: suggest this

### ISSUE THREAD

**Issue by stuartlangridge** [popey/unsnap#15]
Apparently one should log out or perhaps restart the machine entirely after installing flatpak, otherwise various desktop integration things such as menus don't work right and apps don't show up. https://github.com/flatpak/flatpak/issues/2886 is an example here.

**Describe the solution you'd like**
The install-flatpak script should perhaps instruct people to sign out and back in, or maybe reboot, whichever is required.

**Describe alternatives you've considered**
The script could actually do the reboot, but this will make people sad.

**Comment by popey** [comment]
Given people may run this in full auto mode, I think it's probably sensible to suggest users logout/in or reboot as the very last step. Not only to resolve the issue of flatpaks appearing in the menu, but also to clear the path in the current shell which may still have memory of snap application paths. If it's in the install-flatpak script, then people may not see it as it flies by along with a ton of flatpak installs. 

Also, this only occurs for people who do not have flatpak already installed - which - frankly is predominantly Ubuntu users, and maybe some Arch users. No hard data to support this, but in my testing, a high number of distros have the flatpak binary already there. 

So we are agreed we should do this, but only for people installing flatpak using unsnap, and only at the end, I think.
