### ISSUE TITLE
Missing report (filtered for reported ones)

### ISSUE THREAD

**Issue by philclifford** [popey/unsnap#19]
anbox
ascii-image-converter
authy
bottom
bpytop
brave
btop
bucklespring
bw
cannonball
caprine
castersoundboard
cheat
clari3d-lite-64
code-insiders
cura-slicer
dotrun
duf-utility
emote
evince
fakecam
fluffychat
foobar2000
fractal
freecad
freemind
glimpse-editor
gnome-3-26-1604
hollywood
joplin-desktop
jupyter
lbry
mqtt-explorer
natron
node
novnc
obs-cli
obsidian
openscad
persepolis
poedit
prusa-slicer
pulsemixer
qr-code-generator-desktop
redis-desktop-manager
shotcut
shutter
software-boutique
ticker
tio
ubuntu-accomplishments
ubuntu-mate-welcome
v4l2-rtspserver
xonotic
zsync

**Comment by philclifford** [comment]
Here are the ones I think I have found on flathub to possibly merge into applist.csv:

caprine,com.sindresorhus.Caprine
evince,org.gnome.Evince
fluffychat,im.fluffychat.Fluffychat
fractal,org.gnome.Fractal
freecad,org.freecadweb.FreeCAD
lbry,io.lbry.lbry-app
natron,fr.natron.Natron
obsidian,md.obsidian.Obsidian
openscad,org.openscad.OpenSCAD
poedit,net.poedit.Poedit
shotcut,org.shotcut.Shotcut
xonotic,org.xonotic.Xonotic

**Comment by philclifford** [comment]
A couple more matches added to #22

**Comment by popey** [comment]
Closing this now we've merged the pr.
