### ISSUE TITLE
Snapstore release

### ISSUE THREAD

**Issue by mackou** [popey/unsnap#24]
It is currently not possible to install unsnap from the snapstore

unsnap available on snapstore

**Comment by popey** [comment]
This is something I have considered. 
As it calls out to various command line utilities which wouldn't exist inside a confined application, I think it would need to be a `classic` snap. As such, it would have to go through review, and I'm not sure it would pass that review process.

**Comment by popey** [comment]
Having looked at the requirements, unsnap wouldn't pass, so I'm going to close this issue, because there's in all likelihood, no chance of getting unsnap in the snap store in a functional state.
Thanks again for filing the issue though.
