### ISSUE TITLE
Only remove matched snaps by default

### ISSUE THREAD

**Issue by popey** [popey/unsnap#27]
At the moment we're a bit brutal in that we may remove *all* snaps even if there's no matching alternative flatpak.

Perhaps for now we should only remove those that successfully matched a flatpak, and offer the option to nuke the full list, but not do that by default.

**Comment by lucasburlingham** [comment]
I was a bit surprised at this behavior (I was expecting some snaps to be moved over, but to remove not the ones without a replacement). 

At least giving the user some output alerting them of the default would be good.
